# Generated by Django 4.2 on 2025-06-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='localisation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
