# Generated by Django 5.2.2 on 2025-06-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0004_profil_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='reservation',
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
